# Stage 1: Get lego binary for SSL cert management
FROM goacme/lego:latest AS lego

# Stage 2: Nginx reverse proxy with SSL support
FROM nginx:1.27-alpine

COPY --from=lego /lego /usr/local/bin/lego
COPY nginx-docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY nginx-docker/nginx-ssl.conf /etc/nginx/templates/
COPY nginx-docker/nginx-ssl-namecheap.conf /etc/nginx/templates/

COPY nginx-docker/ssl-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80 443

ENTRYPOINT ["/entrypoint.sh"]
